# Tarea S4 T02
## Allison Garces

### Ejercicio 1
Descarga el fecha siete Airlines Delay: Airline on-time statistics and delay causas y cárgalo en un Pandas Dataframe. Explora los datos que contiene, explica brevemente qué variables existen y queda únicamente con las columnas que consideres relevantes.

In [1]:
#Importar librerias
import pandas as pd
import numpy as np

In [2]:
#Importar el dataset
datos = pd.read_csv("DelayedFlights.csv", sep=";", index_col="Column1")
df = pd.DataFrame(data=datos)

In [3]:
#Seleccionamos aleatoriamente solo 200.000 registros
df = datos.sample(200000)

In [4]:
#Seleccion de Columnas relevantes (Mostrando solo 10 primeras filas)
df[["Month", "DayofMonth","DayOfWeek","DepTime","CRSDepTime","CRSDepTime","CRSArrTime","UniqueCarrier","FlightNum","AirTime",
    "ArrDelay","DepDelay","Distance","TaxiIn","TaxiOut","Diverted","CarrierDelay","WeatherDelay","NASDelay",
    "SecurityDelay","LateAircraftDelay"][10:]]

,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Column1,,,,,,,,,,,
2055283,2230.0,2070,347,40.0,300,0,2070.0,0.0,160.0,0.0,0.0
1578154,-10.0,80,304,40.0,110,0,NaN,NaN,NaN,NaN,NaN
2857753,170.0,310,518,40.0,140,0,170.0,0.0,0.0,0.0,0.0
2763829,200.0,70,2562,50.0,120,0,200.0,0.0,0.0,0.0,0.0
1277507,440.0,570,495,60.0,90,0,50.0,0.0,0.0,0.0,390.0
...,...,...,...,...,...,...,...,...,...,...,...
1435807,380.0,420,1515,90.0,140,0,350.0,0.0,0.0,0.0,30.0
998387,690.0,810,562,20.0,80,0,0.0,0.0,0.0,0.0,690.0
484198,40.0,100,1090,40.0,240,0,NaN,NaN,NaN,NaN,NaN
731911,210.0,200,84,150.0,190,0,210.0,0.0,0.0,0.0,0.0
2364320,-60.0,70,1635,150.0,130,0,NaN,NaN,NaN,NaN,NaN

### Ejercicio 2 (A)

In [5]:
#Resumen de estadistica descriptiva General
#Columnas categoricas
#Promedio (mean), Desviacion estandard (std) , Valor minimo, Valor maximo ,Cuartiles (25%, 50% y 75%)

df.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,DepDelay,Distance,TaxiIn,TaxiOut,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,200000.0,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,199284.000000,200000.000000,200000.000000,199284.000000,...,200000.000000,200000.000000,199284.000000,200000.000000,200000.000000,130608.000000,130608.000000,130608.000000,130608.000000,130608.000000
mean,2008.0,3.383300,15.447770,3.999330,15192.759700,1467.890430,16101.022561,1630.587205,2218.035775,1316.157444,...,427.323400,750.362115,66.927852,180.066500,0.003580,188.672363,35.561451,144.256860,0.937385,253.522832
std,0.0,1.698109,8.848544,1.972858,4501.838036,425.328888,5464.282707,465.681184,1931.601303,704.567234,...,525.360515,559.758814,50.253266,136.871477,0.059726,431.092452,210.608092,327.516491,20.491958,412.419836
min,2008.0,1.000000,1.000000,1.000000,10.000000,1.000000,10.000000,0.000000,1.000000,150.000000,...,60.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2008.0,2.000000,8.000000,2.000000,12020.000000,1134.000000,13150.000000,1321.000000,621.000000,800.000000,...,120.000000,337.000000,40.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2008.0,3.000000,15.000000,4.000000,15440.000000,1510.000000,17140.000000,1705.000000,1569.000000,1150.000000,...,240.000000,602.000000,50.000000,140.000000,0.000000,20.000000,0.000000,20.000000,0.000000,90.000000
75%,2008.0,5.000000,23.000000,6.000000,19010.000000,1820.000000,20300.000000,2012.000000,3589.000000,1630.000000,...,530.000000,987.000000,80.000000,210.000000,0.000000,210.000000,0.000000,140.000000,0.000000,330.000000
max,2008.0,6.000000,31.000000,7.000000,24000.000000,2359.000000,24000.000000,2400.000000,7829.000000,6930.000000,...,15450.000000,4962.000000,2000.000000,3050.000000,1.000000,15420.000000,11480.000000,10240.000000,2800.000000,9250.000000

In [6]:
#Estadisticas que considero relevantes

print("Veces que fue desviado un avion, 0 = No, 1 = Si")
df['Diverted'].value_counts()

Veces que fue desviado un avion, 0 = No, 1 = Si

0    199284
1       716
Name: Diverted, dtype: int64

In [7]:
#Estadisticas que considero relevantes
print("Los valores unicos de la columna 'UniqueCarrier' son los siguientes: \n \n",df["UniqueCarrier"].unique())

Los valores unicos de la columna 'UniqueCarrier' son los siguientes:

 ['US' 'MQ' '9E' 'HA' 'XE' 'YV' 'EV' 'NW' 'AA' 'WN' 'UA' 'DL' 'FL' 'CO'
 'AS' 'B6' 'OO' 'OH' 'F9' 'AQ']

In [8]:
#Estadisticas que considero relevantes
print("Mayor tiempo de retraso en minutos:", df["CarrierDelay"].max())

Mayor tiempo de retraso en minutos: 15420.0

### Ejercicio 2 (B)

In [9]:
#Encuentra cuántos datos faltantes hay por columna.

df.isnull().sum()

Year                     0
Month                    0
DayofMonth               0
DayOfWeek                0
DepTime                  0
CRSDepTime               0
ArrTime                716
CRSArrTime               0
UniqueCarrier            0
FlightNum                0
TailNum                  1
ActualElapsedTime      716
CRSElapsedTime          31
AirTime                716
ArrDelay               716
DepDelay                 0
Distance                 0
TaxiIn                 716
TaxiOut                  0
Diverted                 0
CarrierDelay         69392
WeatherDelay         69392
NASDelay             69392
SecurityDelay        69392
LateAircraftDelay    69392
dtype: int64

### Ejercicio 2 (C)

In [10]:
#Crea nuevas columnas (velocidad media del vuelo, si ha llegado tarde o no...).
df['¿Llego tarde?'] = ["Si" if s >=1 else "No" for s in df['LateAircraftDelay']] 

df.head(20)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,Distance,TaxiIn,TaxiOut,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,¿Llego tarde?
Column1,,,,,,,,,,,,,,,,,,,,,
2055283,2008,4,10,4,15350,1208,16100.0,1227,US,267,...,347,40.0,300,0,2070.0,0.0,160.0,0.0,0.0,No
1578154,2008,3,12,3,14380,1430,15390.0,1540,MQ,3777,...,304,40.0,110,0,NaN,NaN,NaN,NaN,NaN,No
2857753,2008,5,21,3,9010,830,11320.0,1115,9E,5728,...,518,40.0,140,0,170.0,0.0,0.0,0.0,0.0,No
2763829,2008,5,25,7,15120,1505,23350.0,2315,HA,40,...,2562,50.0,120,0,200.0,0.0,0.0,0.0,0.0,No
1277507,2008,3,28,5,19370,1840,21140.0,2030,XE,619,...,495,60.0,90,0,50.0,0.0,0.0,0.0,390.0,Si
3143305,2008,6,25,3,19240,1855,21320.0,2114,YV,7281,...,1297,40.0,100,0,180.0,0.0,0.0,0.0,0.0,No
2180713,2008,4,15,2,17530,1545,18370.0,1635,MQ,3736,...,134,50.0,70,0,0.0,0.0,0.0,0.0,1220.0,Si
327700,2008,1,28,1,23030,2126,340.0,2317,EV,4304,...,554,40.0,100,0,770.0,0.0,0.0,0.0,0.0,No
1028301,2008,2,3,7,14020,1353,15260.0,1518,NW,1532,...,393,60.0,210,0,NaN,NaN,NaN,NaN,NaN,No
2871229,2008,5,7,3,19070,1740,20220.0,1845,AA,357,...,641,110.0,200,0,700.0,0.0,100.0,0.0,170.0,Si
1875987,2008,4,28,1,19500,1910,21010.0,2025,WN,2730,...,308,80.0,140,0,0.0,0.0,0.0,0.0,360.0,Si
2480468,2008,5,30,5,21340,2110,22500.0,2235,WN,989,...,479,40.0,70,0,0.0,0.0,90.0,0.0,60.0,Si
9194,2008,1,6,7,14440,1400,15320.0,1450,WN,700,...,189,30.0,90,0,40.0,0.0,0.0,0.0,380.0,Si
1405921,2008,3,19,3,8420,835,10420.0,1031,UA,301,...,1452,90.0,190,0,NaN,NaN,NaN,NaN,NaN,No
305556,2008,1,17,4,23020,2235,6350.0,606,DL,1478,...,2139,100.0,240,0,270.0,0.0,20.0,0.0,0.0,No
426416,2008,1,1,2,13530,1338,16560.0,1636,NW,242,...,1127,50.0,130,0,150.0,0.0,50.0,0.0,0.0,No
1321768,2008,3,21,5,8070,715,9170.0,846,YV,7070,...,251,50.0,80,0,310.0,0.0,0.0,0.0,0.0,No
1615253,2008,3,6,4,19440,1910,190.0,2340,NW,568,...,1501,70.0,110,0,340.0,0.0,50.0,0.0,0.0,No
1445745,2008,3,7,5,20280,2014,21540.0,2155,US,550,...,868,40.0,210,0,NaN,NaN,NaN,NaN,NaN,No
341970,2008,1,31,4,10070,955,11510.0,1155,EV,4780,...,644,40.0,210,0,NaN,NaN,NaN,NaN,NaN,No

In [11]:
df['Velocidad Vuelo'] = (df['Distance'] / df['ArrTime'])
df.head(10)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,¿Llego tarde?,Velocidad Vuelo
Column1,,,,,,,,,,,,,,,,,,,,,
2055283,2008,4,10,4,15350,1208,16100.0,1227,US,267,...,40.0,300,0,2070.0,0.0,160.0,0.0,0.0,No,0.021553
1578154,2008,3,12,3,14380,1430,15390.0,1540,MQ,3777,...,40.0,110,0,NaN,NaN,NaN,NaN,NaN,No,0.019753
2857753,2008,5,21,3,9010,830,11320.0,1115,9E,5728,...,40.0,140,0,170.0,0.0,0.0,0.0,0.0,No,0.045760
2763829,2008,5,25,7,15120,1505,23350.0,2315,HA,40,...,50.0,120,0,200.0,0.0,0.0,0.0,0.0,No,0.109722
1277507,2008,3,28,5,19370,1840,21140.0,2030,XE,619,...,60.0,90,0,50.0,0.0,0.0,0.0,390.0,Si,0.023415
3143305,2008,6,25,3,19240,1855,21320.0,2114,YV,7281,...,40.0,100,0,180.0,0.0,0.0,0.0,0.0,No,0.060835
2180713,2008,4,15,2,17530,1545,18370.0,1635,MQ,3736,...,50.0,70,0,0.0,0.0,0.0,0.0,1220.0,Si,0.007295
327700,2008,1,28,1,23030,2126,340.0,2317,EV,4304,...,40.0,100,0,770.0,0.0,0.0,0.0,0.0,No,1.629412
1028301,2008,2,3,7,14020,1353,15260.0,1518,NW,1532,...,60.0,210,0,NaN,NaN,NaN,NaN,NaN,No,0.025754
2871229,2008,5,7,3,19070,1740,20220.0,1845,AA,357,...,110.0,200,0,700.0,0.0,100.0,0.0,170.0,Si,0.031701

### Ejercicio 2 (D)

In [12]:
df['CarrierDelay'].fillna(df['CarrierDelay'].mean(), inplace=True)
print('Columna Carrier Delay, rellenando Nan con la Media:')
print(df['CarrierDelay'])

Columna Carrier Delay, rellenando Nan con la Media:
Column1
2055283    2070.000000
1578154     188.672363
2857753     170.000000
2763829     200.000000
1277507      50.000000
              ...
1435807     350.000000
998387        0.000000
484198      188.672363
731911      210.000000
2364320     188.672363
Name: CarrierDelay, Length: 200000, dtype: float64

In [13]:
#Aerolinea con mas retrasos
retrasos = df['CarrierDelay'] >= 1
retrasos_aerolinea = df[retrasos]
retrasos_aerolinea['UniqueCarrier'].value_counts()

WN    31238
AA    13236
UA    10048
MQ     9658
OO     8455
US     7630
XE     7567
NW     7200
DL     7020
EV     6564
CO     5980
YV     4418
9E     3743
OH     3610
FL     3588
B6     3013
F9     2416
AS     2217
HA      455
AQ      129
Name: UniqueCarrier, dtype: int64

In [14]:
df.to_csv('DelayedFlights1.csv')